// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2Qj15fBXU4Z4G6W8yzQ-IHJa5G6MbB0',
    appId: '1:564757927514:android:0f86f04a24eb1ccad86a63',
    messagingSenderId: '564757927514',
    projectId: 'astroadmin-366d8',
    storageBucket: 'astroadmin-366d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GclK4kuCI6TZt4githqH4HcgzEEkNdg',
    appId: '1:564757927514:ios:27a76346522a4276d86a63',
    messagingSenderId: '564757927514',
    projectId: 'astroadmin-366d8',
    storageBucket: 'astroadmin-366d8.appspot.com',
    androidClientId: '564757927514-jsueb78smh5e00qqg5avf37je0lk2r5l.apps.googleusercontent.com',
    iosClientId: '564757927514-e4blgi1qbvbiq0bl0hefui73j5sj0fbt.apps.googleusercontent.com',
    iosBundleId: 'com.vidcall.tws.youtube',
  );
}
